### ISSUE TITLE
Only reserved document ids may start with underscore.

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/xmltoldmigration#12]
With current xmltold...;

    java -jar target/xmltoldmigration-0.2.0.jar -writefiles -useCouchdb -datadir ../full20170306-1408/db/tbrc/ -outdir ../tbrc-turtle

> Exception in thread "main" org.ektorp.DbAccessException: 400:Bad Request
URI: /bdrc_outline/_:b0
Response Body: 
{
  "error" : "illegal_docid",
  "reason" : "Only reserved document ids may start with underscore."
}
	at org.ektorp.http.StdResponseHandler.createDbAccessException(StdResponseHandler.java:50)
	at org.ektorp.http.StdResponseHandler.error(StdResponseHandler.java:91)
	at org.ektorp.http.RestTemplate.handleVoidResponse(RestTemplate.java:117)
	at org.ektorp.http.RestTemplate.put(RestTemplate.java:59)
	at org.ektorp.impl.StdCouchDbConnector.create(StdCouchDbConnector.java:140)
	at io.bdrc.xmltoldmigration.MigrationHelpers.jsonObjectToCouch(MigrationHelpers.java:323)
	at io.bdrc.xmltoldmigration.MigrationHelpers.convertOneFile(MigrationHelpers.java:526)
	at io.bdrc.xmltoldmigration.MigrationApp.migrateOneFile(MigrationApp.java:138)
	at io.bdrc.xmltoldmigration.MigrationApp.lambda$migrateType$0(MigrationApp.java:158)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)

**Comment by xristy** [comment]
After updating to include latest commits the error has changed to:

> $ java -jar target/xmltoldmigration-0.2.0.jar -writefiles -useCouchdb -datadir ../full20170306-1408/db/tbrc/ -outdir ../new-tbrc-jsonld/
sending JSON documents to CouchDB
writing files in ../new-tbrc-jsonld/
creating directory: ../new-tbrc-jsonld/
creating directory: ../new-tbrc-jsonld/outlines
converting 1973 outline files
Exception in thread "main" java.lang.NullPointerException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at io.bdrc.xmltoldmigration.MigrationApp.migrateType(MigrationApp.java:158)
	at io.bdrc.xmltoldmigration.MigrationApp.main(MigrationApp.java:197)
Caused by: java.lang.NullPointerException
	at com.fasterxml.jackson.databind.type.ResolvedRecursiveType.equals(ResolvedRecursiveType.java:103)
	at com.fasterxml.jackson.databind.type.TypeBindings$AsKey.equals(TypeBindings.java:458)
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1035)
	at java.util.concurrent.ConcurrentHashMap.putIfAbsent(ConcurrentHashMap.java:1535)
	at com.fasterxml.jackson.databind.util.LRUMap.putIfAbsent(LRUMap.java:64)
	at com.fasterxml.jackson.databind.type.TypeFactory._fromClass(TypeFactory.java:1274)
	at com.fasterxml.jackson.databind.type.TypeFactory._fromParamType(TypeFactory.java:1384)
	at com.fasterxml.jackson.databind.type.TypeFactory._fromAny(TypeFactory.java:1154)
	at com.fasterxml.jackson.databind.type.TypeFactory._resolveSuperClass(TypeFactory.java:1285)
	at com.fasterxml.jackson.databind.type.TypeFactory._fromClass(TypeFactory.java:1246)
	at com.fasterxml.jackson.databind.type.TypeFactory._fromAny(TypeFactory.java:1150)
	at com.fasterxml.jackson.databind.type.TypeFactory.constructType(TypeFactory.java:618)
	at com.fasterxml.jackson.databind.cfg.MapperConfig.constructType(MapperConfig.java:290)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:496)
	at com.fasterxml.jackson.databind.SerializerProvider.findTypedValueSerializer(SerializerProvider.java:697)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:270)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1419)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1147)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:1020)
	at org.ektorp.http.StdResponseHandler.toPrettyString(StdResponseHandler.java:55)
	at org.ektorp.http.StdResponseHandler.createDbAccessException(StdResponseHandler.java:46)
	at org.ektorp.http.StdResponseHandler.error(StdResponseHandler.java:91)
	at org.ektorp.http.RestTemplate.handleVoidResponse(RestTemplate.java:117)
	at org.ektorp.http.RestTemplate.put(RestTemplate.java:59)
	at org.ektorp.impl.StdCouchDbConnector.create(StdCouchDbConnector.java:140)
	at io.bdrc.xmltoldmigration.MigrationHelpers.jsonObjectToCouch(MigrationHelpers.java:323)
	at io.bdrc.xmltoldmigration.MigrationHelpers.convertOneFile(MigrationHelpers.java:526)
	at io.bdrc.xmltoldmigration.MigrationApp.migrateOneFile(MigrationApp.java:138)
	at io.bdrc.xmltoldmigration.MigrationApp.lambda$migrateType$0(MigrationApp.java:158)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by xristy** [comment]
apparently I tried using xmltold... too early, before it was sufficiently baked.
