### ISSUE TITLE
OutOfMemoryError in Works

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/xmltoldmigration#19]
Running:

     time java -jar target/xmltoldmigration-0.2.0.jar -useCouchdb -datadir ../full20170817-1508/db/tbrc/ -outdir ../bdrc-turtle/

I got:

> converting 55731 work files
adding missing symetric triples in 70 files
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.lang.AbstractStringBuilder.<init>(AbstractStringBuilder.java:68)
	at java.lang.StringBuilder.<init>(StringBuilder.java:89)
	at com.github.jsonldjava.core.Context.compactIri(Context.java:781)
	at com.github.jsonldjava.core.Context.compactIri(Context.java:717)
	at com.github.jsonldjava.core.JsonLdApi.compact(JsonLdApi.java:335)
	at com.github.jsonldjava.core.JsonLdApi.compact(JsonLdApi.java:349)
	at com.github.jsonldjava.core.JsonLdApi.compact(JsonLdApi.java:349)
	at com.github.jsonldjava.core.JsonLdApi.compact(JsonLdApi.java:349)
	at com.github.jsonldjava.core.JsonLdApi.compact(JsonLdApi.java:349)
	at com.github.jsonldjava.core.JsonLdApi.compact(JsonLdApi.java:349)
	at com.github.jsonldjava.core.JsonLdApi.compact(JsonLdApi.java:168)
	at com.github.jsonldjava.core.JsonLdProcessor.frame(JsonLdProcessor.java:319)
	at org.apache.jena.riot.writer.JsonLDWriter.toJsonLDJavaAPI(JsonLDWriter.java:224)
	at io.bdrc.xmltoldmigration.MigrationHelpers.modelToJsonObject(MigrationHelpers.java:346)
	at io.bdrc.xmltoldmigration.MigrationHelpers.outputOneModel(MigrationHelpers.java:530)
	at io.bdrc.xmltoldmigration.MigrationApp.migrateType(MigrationApp.java:226)
	at io.bdrc.xmltoldmigration.MigrationApp.main(MigrationApp.java:293)
real	76m24.487s
user	207m51.565s
sys	5m43.475s

**Comment by eroux** [comment]
Hmm... not sure I can do much but I'll try...

**Comment by xristy** [comment]
I'll add more memory. I was guessing that it might have run amok during _adding missing symetric triples in 70 files_.

**Comment by xristy** [comment]
I ran the latest with 4GB and still it fails. I'm pretty sure there/s a non-terminating recursion:

> $ time java -Xmx4096m -jar xmltoldmigration-0.2.0.jar -useCouchdb -datadir full20170817-1508/db/tbrc/ -outdir bdrc-turtle/
sending JSON documents to CouchDB
writing files in bdrc-turtle/
converting 2033 outline files
converting 18428 person files
adding missing symetric triples in 6054 files
recorded 437 events to migrate to places
creating directory: bdrc-turtle/places
converting 55236 place files
adding missing symetric triples in 28579 files
creating directory: bdrc-turtle/offices
converting 382 office files
creating directory: bdrc-turtle/corporations
converting 251 corporation files
creating directory: bdrc-turtle/lineages
converting 2001 lineage files
creating directory: bdrc-turtle/topics
converting 3617 topic files
creating directory: bdrc-turtle/items
converting 55732 work files
adding missing symetric triples in 46 files
Exception in thread "main" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.LinkedHashMap.newNode(LinkedHashMap.java:256)
	at java.util.HashMap.putVal(HashMap.java:630)
	at java.util.HashMap.put(HashMap.java:611)
	at com.github.jsonldjava.core.JsonLdApi.compact(JsonLdApi.java:235)
	at com.github.jsonldjava.core.JsonLdApi.compact(JsonLdApi.java:349)
	at com.github.jsonldjava.core.JsonLdApi.compact(JsonLdApi.java:349)
	at com.github.jsonldjava.core.JsonLdApi.compact(JsonLdApi.java:349)
	at com.github.jsonldjava.core.JsonLdApi.compact(JsonLdApi.java:349)
	at com.github.jsonldjava.core.JsonLdApi.compact(JsonLdApi.java:349)
	at com.github.jsonldjava.core.JsonLdApi.compact(JsonLdApi.java:349)
	at com.github.jsonldjava.core.JsonLdApi.compact(JsonLdApi.java:349)
	at com.github.jsonldjava.core.JsonLdApi.compact(JsonLdApi.java:168)
	at com.github.jsonldjava.core.JsonLdProcessor.frame(JsonLdProcessor.java:319)
	at org.apache.jena.riot.writer.JsonLDWriter.toJsonLDJavaAPI(JsonLDWriter.java:224)
	at io.bdrc.xmltoldmigration.MigrationHelpers.modelToJsonObject(MigrationHelpers.java:345)
	at io.bdrc.xmltoldmigration.MigrationHelpers.outputOneModel(MigrationHelpers.java:529)
	at io.bdrc.xmltoldmigration.MigrationApp.migrateType(MigrationApp.java:227)
	at io.bdrc.xmltoldmigration.MigrationApp.main(MigrationApp.java:294)
real	65m12.061s
user	33m40.216s
sys	0m29.932s

**Comment by eroux** [comment]
The code that does the transformation to jsonld is now in git-to-dbs, but I don't think the problem persists, closing
