### ISSUE TITLE
transfer to couchdb broken

### ISSUE THREAD

**Issue by xristy** [BuddhistDigitalResourceCenter/xmltoldmigration#4]
I added a flag `-useCouchdb` to `MigrationApp` which sets `usecouchdb = true` in `MigrationHelpers`.

Then I ran:

    java -jar target/xmltoldmigration-0.1-jar-with-dependencies.jar -useCouchdb

which now breaks with:

>SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
creating directory: tbrc-jsonld/
creating directory: tbrc-jsonld/places
converting 55230 place files
Exception in thread "main" java.lang.ExceptionInInitializerError
	at io.bdrc.xmltoldmigration.MigrationHelpers.modelToOutputStream(MigrationHelpers.java:254)
	at io.bdrc.xmltoldmigration.MigrationHelpers.modelToFileName(MigrationHelpers.java:318)
	at io.bdrc.xmltoldmigration.MigrationHelpers.convertOneFile(MigrationHelpers.java:409)
	at io.bdrc.xmltoldmigration.MigrationApp.migrateOneFile(MigrationApp.java:126)
	at io.bdrc.xmltoldmigration.MigrationApp.lambda$migrateType$0(MigrationApp.java:146)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at io.bdrc.xmltoldmigration.MigrationApp.migrateType(MigrationApp.java:146)
	at io.bdrc.xmltoldmigration.MigrationApp.main(MigrationApp.java:162)
Caused by: java.lang.NullPointerException
	at org.apache.jena.query.ARQ.isTrue(ARQ.java:633)
	at org.apache.jena.riot.system.RiotLib.<clinit>(RiotLib.java:63)
	... 20 more

It may be easier for you to debug this than for me. I didn't realize this area was being changed.

I thought that the usecouchdb was so you could do conversion testing without having to wait for couchdb to be populated -- it does run rather faster with populating couchdb.

**Comment by eroux** [comment]
I'm surprised the .jar file worked before, did it really? I've never managed to make the .jar file work, for reasons that seem to be linked with some black magic that needs to be done when using jena with maven... Anyway, I advise running `mvn exec:java` in the meantime. I'll try again to figure out how to build a .jar with jena, but it will require a few hours... I'll do that tomorrow

**Comment by eroux** [comment]
I can confirm that the .jar never worked for me, I tried by getting back to commit 4abf805 for instance and got the same error... can you tell me if you have it too?

**Comment by xristy** [comment]
Yes I can confirm that running the jar fails with the NPE at ARQ.java:633.

I'm lacking sufficient chops to know how to run:

    mvn exec:java -Dexec.mainClass=io.bdrc.xmltoldmigration.MigrationApp

with the command line arg `-useCouchdb`.

I imagine there's a way to do that. I think having the option of running the migration with and without uploading to couchdb is sensible.

Also I need a walk-through to learn what:

    mvn exec:java -Dexec.mainClass=io.bdrc.xmltoldmigration.MigrationApp

does. It runs java as follows so the myriad dependencies are being class loaded via some maven feature that I have no experience with:

    /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/bin/java -classpath /usr/local/apache-maven-3.2.3/boot/plexus-classworlds-2.5.1.jar -Dclassworlds.conf=/usr/local/apache-maven-3.2.3/bin/m2.conf -Dmaven.home=/usr/local/apache-maven-3.2.3 org.codehaus.plexus.classworlds.launcher.Launcher exec:java -Dexec.mainClass=io.bdrc.xmltoldmigration.MigrationApp

I'd guess that something(s) that's getting packaged in the `xmltoldmigration-0.1-jar-with-dependencies.jar` is a different version than what's referenced via the maven class loading.

The NPE is happening in MigrationHelpers when preparing the `PrefixMap` for the first Place document:

        DatasetGraph g = DatasetFactory.create(m).asDatasetGraph();
        PrefixMap pm = RiotLib.prefixMap(g);

So it really seems actually disturbing that code way inside a chain of calls from `MigrationApp` through `MigrationHelpers` is failing when invoked via `main` in the jar vs presumably the same sequence of calls from the `mvn exec:java` invocation.

**Comment by eroux** [comment]
Well, we're at the same point then, I'll spend a day or two understanding maven or maybe finding an alternative...
